name: builder-image

on: [workflow_dispatch]

jobs:
  build-image:
    runs-on: self-built-ubuntu
    env:
      CLANG_VERSION: 10
    strategy:
      matrix:
        os:
          - name: ubuntu
#          - name: centos
    steps:
    - name: Remove prvious cloned repo
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY|awk -F '\/' '{print $2}')
        CHECKOUT_PATH="${RUNNER_WORKDIR}/${REPO_NAME}/${REPO_NAME}"
        if [ -d $CHECKOUT_PATH ]; then
          sudo rm -rf "$CHECKOUT_PATH/*"
        fi
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cd Builds/containers/
        docker build -t registry.gitlab.com/shichengsg001/demo:${{ matrix.os.name }}_rippled_build --build-arg CI_USE=true . -f ${{ matrix.os.name }}-builder/Dockerfile
    - name: Push
      run: |
        docker login registry.gitlab.com/shichengsg001/demo -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_TOKEN }}"
        docker push registry.gitlab.com/shichengsg001/demo:${{ matrix.os.name }}_rippled_build
